function ShowPositions(jsonServer){'use strict';var accountName=dc.rowChart('#account-name');var assetsName=dc.rowChart('#assets-name');var regionChart=dc.pieChart('#region-chart');var assetChart=dc.pieChart('#asset-chart');var currencyChart=dc.pieChart('#currency-chart');var valueChart=dc.pieChart('#value-chart');var data=JSON.parse(jsonServer);var ndx=crossfilter(data);var all=ndx.groupAll();var yearlyDimension=ndx.dimension(function(d){return d.firstname;});var accountHolding=ndx.dimension(function(d){return d.accountName;});var accountHoldingGroup=accountHolding.group().reduceSum(function(d){return d.positionValueInBaseCurrency;});var currency=ndx.dimension(function(d){return d.assetCurrency;});var currencyGroup=currency.group();var assets=ndx.dimension(function(d){return d.assetName;});var assetsGroup=assets.group();var region=ndx.dimension(function(d){return d.region;});var regionGroup=region.group();var asset=ndx.dimension(function(d){return d.assetClass;});var assetGroup=asset.group();var accountValue=ndx.dimension(function(d){return d.assetName;});var accountValueGroup=accountValue.group().reduceSum(function(d){return Math.round(d.positionValueInBaseCurrency*100)/ 100;
});accountName.width(850).height(250).margins({top:20,left:10,right:10,bottom:20}).group(accountHoldingGroup).dimension(accountHolding).ordinalColors(['#3182bd','#6baed6','#9ecae1','#c6dbef','#dadaeb']).label(function(d){return d.key;}).title(function(d){return d.value;}).elasticX(true).xAxis().ticks(4);assetsName.width(300).height(850).margins({top:20,left:10,right:10,bottom:20}).group(assetsGroup).dimension(assets).ordinalColors(['#3182bd','#6baed6','#9ecae1','#c6dbef','#dadaeb']).label(function(d){return d.key;}).title(function(d){return d.accountName;}).elasticX(true).xAxis().ticks(4);currencyChart.width(280).height(280).radius(120).innerRadius(30).dimension(currency).group(currencyGroup).label(function(d){if(currencyChart.hasFilter()&&!currencyChart.hasFilter(d.key)){return d.key+'(0%)';}
var label=d.key;if(all.value()){label+='('+(d.value/all.value()*100).toFixed(0)+'%)';}
return label;});assetChart.width(280).height(280).radius(120).innerRadius(30).dimension(asset).group(assetGroup).label(function(d){if(assetChart.hasFilter()&&!assetChart.hasFilter(d.key)){return d.key+'(0%)';}
var label=d.key;if(all.value()){label+='('+(d.value/all.value()*100).toFixed(0)+'%)';}
return label;});valueChart.width(280).height(280).radius(120).innerRadius(30).dimension(accountValue).group(accountValueGroup).label(function(d){if(valueChart.hasFilter()&&!valueChart.hasFilter(d.key)){return d.key+'(0%)';}
var postionGroupByAssetName=ndx.dimension(function(d){return d.assetName;});var positionTotal=0;var dataArray=postionGroupByAssetName.top(Infinity);for(var i=0;i<dataArray.length;i++){positionTotal=positionTotal
+ parseFloat(dataArray[i].positionValueInBaseCurrency);}
var label=d.key;if(positionTotal!=0){label+='('+(d.value/positionTotal*100).toFixed(0)
+'%)';}
postionGroupByAssetName.dispose();return label;});regionChart.width(280).height(280).radius(120).innerRadius(30).dimension(region).group(regionGroup).label(function(d){if(regionChart.hasFilter()&&!regionChart.hasFilter(d.key)){return d.key+'(0%)';}
var label=d.key;if(all.value()){label+='('+(d.value/all.value()*100).toFixed(0)+'%)';}
return label;});dc.dataCount('.dc-data-count').dimension(ndx).group(all).html({some:'<strong>%filter-count</strong> selected out of <strong>%total-count</strong> records'
+' | <a href=\'javascript:dc.filterAll(); dc.renderAll();\'\'>Reset All</a>',all:'All records selected. Please click on the graph to apply filters.'});dc.dataTable('.dc-data-table').dimension(yearlyDimension).group(function(d){return'Asset Class: '+ d.assetClass;}).size(60).columns([{label:'Account Name',format:function(d){return'<span style="float: left;">'
+ d.accountName+'</span>';}},{label:'Asset Name',format:function(d){return'<span style="float: left;">'
+ d.assetName+' '+'('
+ d.assetCurrency+')'+'</span>';}},{label:'Asset Class',format:function(d){return'<span style="float: right;">'
+ d.assetClass+'</span>';;}},{label:'Region',format:function(d){return'<span style="float: right; text-align:right;">'
+ d.region+'</span>';}},{label:'Position Value',format:function(d){var x=Math.round(d.positionValue*100)/ 100;
x=x.toFixed(2);return'<span style="float: right;">'
+ x.toString().replace(/\B(?=(\d{3})+(?!\d))/g,",")+' '
+ d.accountCurrency+'</span>';}}]).sortBy(function(d){return-d.positionValue;}).renderlet(function(table){table.selectAll('.dc-table-group').classed('info',true);});dc.renderAll();}