function refreshMenuHandler(){$('#side-menu').metisMenu();$('.close-canvas-menu').off("click");$('.close-canvas-menu').click(function(){$("body").toggleClass("mini-navmatbar");SmoothlyMenu();});$('.right-sidebar-toggle').off("click");$('.right-sidebar-toggle').click(function(){$('#right-sidebar').toggleClass('sidebar-open');});$('.sidebar-container').slimScroll({height:'100%',railOpacity:0.4,wheelStep:10});$('.check-link').off("click");$('.check-link').click(function(){var button=$(this).find('i');var label=$(this).next('span');button.toggleClass('fa-check-square').toggleClass('fa-square-o');label.toggleClass('todo-completed');return false;});$('.navmatbar-minimalize').off("click");$('.navmatbar-minimalize').click(function(){$("#material-body").toggleClass("mini-navmatbar");SmoothlyMenu();});}
function minimizeMenu(){$("#material-body").removeClass("mini-navmatbar");SmoothlyMenu();}
function makeMenuBarAutoHide(hide){if($(this).width()<1301){$('#material-body').addClass('body-small').removeClass('mini-navmatbar');}else{$('#material-body').removeClass('body-small');}}
function initMaterialMenu(){makeMenuBarAutoHide();$('#side-menu').metisMenu();$('.close-canvas-menu').click(function(){$("body").toggleClass("mini-navmatbar");SmoothlyMenu();});$('.right-sidebar-toggle').off("click");$('.right-sidebar-toggle').click(function(){$('#right-sidebar').toggleClass('sidebar-open');});$('.sidebar-container').slimScroll({height:'100%',railOpacity:0.4,position:'left',wheelStep:10});$('.check-link').click(function(){var button=$(this).find('i');var label=$(this).next('span');button.toggleClass('fa-check-square').toggleClass('fa-square-o');label.toggleClass('todo-completed');return false;});$('.navmatbar-minimalize').off("click");$('.navmatbar-minimalize').click(function(){$("#material-body").toggleClass("mini-navmatbar");SmoothlyMenu();});$(window).bind("load",function(){if($("#material-body").hasClass('fixed-sidebar')){$('.sidebar-collapse').slimScroll({height:'100%',railOpacity:0.9});}});function fix_height(){var heightWithoutNavbar=$("#material-body > #wrapper").height()- 61;$(".sidebard-panel").css("min-height",heightWithoutNavbar+"px");var navbarHeigh=$('nav.navmatbar-default').height();var wrapperHeigh=$('#page-wrapper').height();var minHeight=0;if(navbarHeigh>wrapperHeigh){minHeight=navbarHeigh;}
if(navbarHeigh<wrapperHeigh){minHeight=$(window).height();}
if($('#material-body').hasClass('fixed-navmat')){minHeight=$(window).height()- 60;}
if(minHeight<1200)
minHeight=1200;$('#page-wrapper').css("min-height",minHeight+"px");}
fix_height();$(window).scroll(function(){if($(window).scrollTop()>0&&!$('#material-body').hasClass('fixed-navmat')){$('#right-sidebar').addClass('sidebar-top');}else{$('#right-sidebar').removeClass('sidebar-top');}});$(window).bind("load resize scroll",function(){if(!$("#material-body").hasClass('body-small')){fix_height();}});$("[data-toggle=popover]").popover();$('.full-height-scroll').slimscroll({height:'100%'})}
$(window).bind("resize",function(){makeMenuBarAutoHide();});function SmoothlyMenu(){if(!$('#material-body').hasClass('mini-navmatbar')||$('#material-body').hasClass('body-small')){$('#side-menu').hide();setTimeout(function(){$('#side-menu').fadeIn(500);},100);}else{$('#side-menu').removeAttr('style');}}
(function($){var strLocation=window.location.href;var strHash=window.location.hash;var strPrevLocation="";var strPrevHash="";var intIntervalTime=100;var fnCleanHash=function(strHash){return(strHash.substring(1,strHash.length));}
var fnCheckLocation=function(){if(strLocation!=window.location.href){strPrevLocation=strLocation;strPrevHash=strHash;strLocation=window.location.href;strHash=window.location.hash;$(window.location).trigger("change",{currentHref:strLocation,currentHash:fnCleanHash(strHash),previousHref:strPrevLocation,previousHash:fnCleanHash(strPrevHash)});}}
setInterval(fnCheckLocation,intIntervalTime);})(jQuery);$(window.location).bind("change",function(objEvent,objData){minimizeMenu();console.log("Tried to collapse menu");});